apiVersion: v1/deployment
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: co1
      image:  nginx:latest
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage
  volumes:
    - name: nginx-storage
      PersistentVolumeClaim:
        claimName: nginx-pvc
