apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: myapp
    team: integration
  spec: 
    containers:
      - name: co1
        image: nginx:latest
        ports:
          -contaierPort: 80 

     
